### ISSUE TITLE
Determine exception within AfterMessageHandled

### ISSUE THREAD

**Issue by JonnyBooker** [rebus-org/Rebus.Events#1]
I am using the IHandlesMessages pattern to handle messages. I have forced an exception within the `Handle` logic and the `AfterMessageHandled` is now being hit. I was wondering if is possible to tell if now the message has handled that you can tell if the handling of a message threw an exception?

```c#
RebusConfigurer.Events(events =>
{
    events.BeforeMessageHandled += (bus, headers, message, context, args) =>
    {
        headers[HandledDateTimeHeaderName] = DateTime.UtcNow.ToString();
    };
    events.BeforeMessageSent += (bus, headers, message, context) =>
    {
        headers[MessageSentDateTimeHeaderName] = DateTime.UtcNow.ToString();
    };

    events.AfterMessageHandled += (bus, headers, message, context, args) =>
    {
        var messageQueueObject = message as IMessageQueueObject;
        var beforeHandledDateTime = DateTime.Parse(headers[HandledDateTimeHeaderName]);
        var difference = DateTime.UtcNow - beforeHandledDateTime;

        //TODO: Determine if message failed handling logic
        //...
    };
    events.AfterMessageSent += (bus, headers, message, context) =>
    {
        var messageQueueObject = message as IMessageQueueObject;
        var beforeHandledDateTime = DateTime.Parse(headers[MessageSentDateTimeHeaderName]);
        var difference = DateTime.UtcNow - beforeHandledDateTime;

        //...
    };
});
```

**Comment by mookid8000** [comment]
While it's not immediately obvious, it IS actually possible to tell that an exception occurred while handling a message from within the `AfterMessageHandled` listener.

As you can see [here](https://github.com/rebus-org/Rebus.Events/blob/master/Rebus.Events/Events/Steps/MessageReceivedStep.cs#L50-L52) the exception gets stashed in the `IncomingStepContext` when caught, allowing you to retrieve it from your listener by calling

    var exceptionOrNull = context.Load<Exception>();

    if (exceptionOrNull == null) return; //< nothing to do

    // inspect exception here - possibly doing this if you want
    // to ignore it:
    args.IgnoreException = true;

**Comment by JonnyBooker** [comment]
Just what I need. Thank you very much!

**Comment by vedaantees-archived** [comment]
for events.AfterMessageHandled += (bus, headers, message, context, args) , I am getting null for IBus. I am using Autofac as DI. Any idea why?

**Comment by mookid8000** [comment]
Thanks @abhay-naik for reporting this 😄 it was a genuine bug, which I have now fixed. The fix is available in Rebus.Events 4.0.1, which is on NuGet.org in a few minutes.

**Comment by vedaantees-archived** [comment]
You are so awesome....thanks so much.
